### ISSUE TITLE
Dockbeat fails with npipe:// socket on Windows; exits with status 1

### ISSUE THREAD

**Issue by godefroi** [Ingensi/dockbeat#142]
I am attempting to run dockbeat on Windows, and am not having success.

```
dockbeat:
  # Defines how often a docker stat is sent to the output
  period: 5

  # Defines the docker socket path
  socket: npipe:////./pipe/docker_engine
```

Dockbeat exits immediately with status 1, and if logging is configured, the following error is logged:

```
2017-02-07T10:31:10-08:00 CRIT Setup returned an error: Unable to create docker client, please check your docker socket/TLS settings: invalid endpoint
```

Dockbeat uses fsouza/go-dockerclient to communicate with Docker, I believe, and go-dockerclient does support npipe connections to docker on Windows (f.e. Registrator works, and uses the same docker client), but dockbeat does not work.
